name: CI
description: Runs Continuous Integration checks
runs:
    using: composite
    steps:
        - name: Set up tools
          uses: dnd-mapp/.github/.github/actions/setup-tools@009a3203e96cba5d053d75f944d5f6ffe4294c76

        - name: Check formatting
          shell: bash
          run: pnpm format:check

        - name: Run linting
          shell: bash
          run: pnpm lint

        - name: Run tests
          shell: bash
          run: pnpm test

        - name: Compile library
          shell: bash
          run: pnpm build
