name: CI
description: Runs Continuous Integration checks
runs:
    using: composite
    steps:
        - name: Set up tools
          uses: dnd-mapp/.github/.github/actions/setup-tools@c78632d4e2a58932d57a301542d1ecd5ae9c8258

        - name: Check formatting
          shell: bash
          run: pnpm format:check

        - name: Run linting
          shell: bash
          run: pnpm lint

        - name: Run tests
          shell: bash
          run: pnpm test

        - name: Compile library
          shell: bash
          run: pnpm build
