name: CI
description: Runs Continuous Integration checks
runs:
    using: composite
    steps:
        - name: Set up tools
          uses: dnd-mapp/.github/.github/actions/setup-tools@49f027b3767592493f303f51af1b4a241f87e22b

        - name: Check formatting
          shell: bash
          run: pnpm format:check

        - name: Run linting
          shell: bash
          run: pnpm lint

        - name: Run tests
          shell: bash
          run: pnpm test

        - name: Compile library
          shell: bash
          run: pnpm build
