name: Publish release
on:
    push:
        branches:
            - main
            - 'release/**'
permissions:
    contents: write
jobs:
    publish-release:
        uses: dnd-mapp/.github/.github/workflows/publish-release.yaml@fb7d2cb1e259f65c841cac6dd9a84896068e9f7a
        secrets:
            app-id: ${{ secrets.AUTH_APP_ID }}
            app-private-key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
