name: Publish release
on:
    push:
        branches:
            - main
            - 'release/**'
permissions:
    contents: write
jobs:
    publish-release:
        uses: dnd-mapp/.github/.github/workflows/publish-release.yaml@9a4924a69aa8b6c62d5cb35240ed4fa00c979c6d
        secrets:
            app-id: ${{ secrets.AUTH_APP_ID }}
            app-private-key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
