name: Publish release
on:
    push:
        branches:
            - main
            - 'release/**'
permissions:
    contents: write
jobs:
    publish-release:
        uses: dnd-mapp/.github/.github/workflows/publish-release.yaml@c3d8e5374660511ad91a0fe705cae3ba4643d674
        secrets:
            app-id: ${{ secrets.AUTH_APP_ID }}
            app-private-key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
