name: Push tag
on:
    push:
        tags:
            - 'v*'
permissions:
    contents: read
    id-token: write
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 0

            - name: CI
              uses: ./.github/actions/ci

            - name: Publish package
              uses: dnd-mapp/.github/.github/actions/publish-npm-package@e447e89f2347766291393f81dc00cbc0877850f5
